name: "🎨 Sync Figma Design Tokens"

on:
  schedule:
    - cron: '0 */6 * * *'     # hver 6. time
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update selv uten diff'
        required: false
        default: 'false'
        type: boolean
  repository_dispatch:
    types: [figma-tokens-updated]

# kreves for å pushe commits
permissions:
  contents: write

# unngå parallelle kjørsler
concurrency:
  group: figma-token-sync
  cancel-in-progress: true

# tilgjengelig for alle job steg
env:
  FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
  FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}

jobs:
  sync-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📚 Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: 🎨 Hent tokens fra Figma
        run: |
          echo "🔍 Fetching latest design tokens from Figma..."
          # Kjør din fetch/transform-kode her:
          # Eksempel: node styles/figma-sync.js
          # For demo lager vi en placeholder hvis mangler:
          mkdir -p styles
          if [ ! -f styles/tokens.css ]; then
            echo "/* initial tokens */" > styles/tokens.css
          fi
          # TODO: erstatt linjen over med faktisk generering av tokens.css

      - name: 🔍 Sjekk endringer i tokens.css
        id: gitcheck
        run: |
          if [ ! -f styles/tokens.css ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            git add -N styles/tokens.css >/dev/null 2>&1 || true
            if git diff --quiet -- styles/tokens.css; then
              echo "changes=false" >> $GITHUB_OUTPUT
            else
              echo "changes=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: 📝 Commit & push
        if: steps.gitcheck.outputs.changes == 'true' || github.event.inputs.force_update == 'true'
        run: |
          git config user.name  "🎨 Figma Token Sync"
          git config user.email "action@github.com"
          git add styles/tokens.css
          git commit -m "🎨 Update design tokens from Figma
          
          - Synced: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          - File: $FIGMA_FILE_ID
          - Trigger: ${{ github.event_name }}"
          git push origin ${{ github.ref_name || 'main' }}

      - name: 🚀 Trigger Vercel deploy (valgfritt)
        if: steps.gitcheck.outputs.changes == 'true' || github.event.inputs.force_update == 'true'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # prj_...
        run: |
          if [ -n "$VERCEL_TOKEN" ] && [ -n "$VERCEL_PROJECT_ID" ]; then
            curl -s -X POST "https://api.vercel.com/v1/integrations/deploy/prj_${VERCEL_PROJECT_ID}/main" \
              -H "Authorization: Bearer ${VERCEL_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{"name":"figma-token-sync","meta":{"githubCommitRef":"main"}}'
          else
            echo "Vercel secrets ikke satt – hopper over deploy."
          fi

      - name: 💬 Oppsummering
        run: |
          if [ "${{ steps.gitcheck.outputs.changes }}" = "true" ] || [ "${{ github.event.inputs.force_update }}" = "true" ]; then
            {
              echo "## 🎨 Design Tokens Updated"
              echo "- Figma File: $FIGMA_FILE_ID"
              echo "- Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
              echo "- Status: ✅ Updated and pushed"
            } >> $GITHUB_STEP_SUMMARY
          else
            {
              echo "## 🎨 No Token Changes"
              echo "- Last Check: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
              echo "- Status: ✅ Up to date"
            } >> $GITHUB_STEP_SUMMARY
          fi
