name: 🎨 Sync Figma Design Tokens

on:
  # Run every 6 hours to check for token updates
  schedule:
    - cron: '0 */6 * * *'

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force token update even if no changes detected'
        required: false
        default: 'false'
        type: boolean

  # Run when Figma webhook is triggered (if configured)
  repository_dispatch:
    types: [figma-tokens-updated]

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    env:
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📚 Install dependencies
        run: npm ci

      - name: 🎨 Sync design tokens from Figma
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
          FORCE_UPDATE: ${{ github.event.inputs.force_update }}
        run: |
          echo "🔍 Fetching latest design tokens from Figma..."
          node styles/figma-sync.js

      - name: 🔍 Check for token changes
        id: git-check
        run: |
          if git diff --quiet styles/tokens.css; then
            echo "No token changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Token changes detected!"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 📝 Commit and push token updates
        if: steps.git-check.outputs.changes == 'true' || github.event.inputs.force_update == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "🎨 Figma Token Sync"
          
          # Add the updated tokens file
          git add styles/tokens.css
          
          # Create commit with detailed message
          COMMIT_MSG="🎨 Update design tokens from Figma\n\n- Synced at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')\n- Figma File ID: ${{ secrets.FIGMA_FILE_ID }}\n- Triggered by: ${{ github.event_name }}\n\nThis commit was automatically generated by the Figma Token Sync workflow."
          
          git commit -m "$COMMIT_MSG"
          
          # Push changes
          git push origin main
          
          echo "✅ Design tokens updated and pushed to main branch"

      - name: 🚀 Trigger Vercel deployment
        if: steps.git-check.outputs.changes == 'true' || github.event.inputs.force_update == 'true'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "🔄 Triggering Vercel deployment with updated tokens..."
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_${{ secrets.VERCEL_PROJECT_ID }}/main" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"name": "figma-token-sync", "meta": {"githubCommitRef": "main"}}'

      - name: 💬 Post summary
        run: |
          if [[ "${{ steps.git-check.outputs.changes }}" == "true" ]]; then
            echo "## 🎨 Design Tokens Updated" >> $GITHUB_STEP_SUMMARY
            echo "Design tokens have been successfully synced from Figma and deployed!" >> $GITHUB_STEP_SUMMARY
            echo "- **Figma File**: ${{ secrets.FIGMA_FILE_ID }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Sync Time**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
            echo "- **Status**: ✅ Updated and deployed" >> $GITHUB_STEP_SUMMARY
          else
            echo "## 🎨 No Token Changes" >> $GITHUB_STEP_SUMMARY
            echo "No design token changes were detected in Figma." >> $GITHUB_STEP_SUMMARY
            echo "- **Last Check**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
            echo "- **Status**: ✅ Up to date" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 🚨 Notify on failure
        if: failure()
        run: |
          echo "## ❌ Token Sync Failed" >> $GITHUB_STEP_SUMMARY
          echo "The Figma token sync workflow failed. Please check the logs for details." >> $GITHUB_STEP_SUMMARY
          echo "- **Time**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "- **Workflow**: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
